function_parameter_count:
  warning: 6  # triggers a warning if more than 5 parameters
  error: 8    # triggers an error if more than 8 parameters
excluded:
  - Pods
disabled_rules:
  - trailing_whitespace
identifier_name:
  excluded: # excluded via string array
    - id
    - URL
    - url
    - app
file_length:
  warning: 500
  error: 1500
type_body_length:
  - 500 # warning
  - 700 # error
cyclomatic_complexity:
  ignores_case_statements: true
function_body_length:
  warning: 150
  error: 300

